---
version: 0.2

phases:
  pre_build:
    commands:
      #- $(aws ecr get-login --no-include-email --region ap-south-1)
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 753613252360.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t html-nginx ."
      - "docker tag html-nginx:latest 753613252360.dkr.ecr.ap-south-1.amazonaws.com/html-nginx:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 753613252360.dkr.ecr.ap-south-1.amazonaws.com/html-nginx:latest"
      - printf '[{"name":"nodecontainer","imageUri":"%s"}]' 753613252360.dkr.ecr.ap-south-1.amazonaws.com/html-nginx:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
