---
version: 0.2

phases:
  pre_build:
    commands:
      #- $(aws ecr get-login --no-include-email --region ap-south-1)
      - aws ecr get-login-password --region us-east-1 | docker login --username 
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t node ."
      - "docker tag node:latest 992382769884dkr.ecr.ap-south-1.amazonaws.com/node:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 992382769884.dkr.ecr.us-east-1.amazonaws.com/testing:latest"
      - printf '[{"name":"nodecontainer","imageUri":"%s"}]' 992382769884.dkr.ecr.us-east-1.amazonaws.com/testing:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
